charmbracelet/huh

examples/bubbletea/main.go
Just a small typo in the example code <3
=> Fix: minor typo

README.md, examples/go.mod, examples/go.sum, examples/theme/catppuccin-theme.png, examples/theme/main.go, examples/theme/theme.tape, go.mod, go.sum, theme.go
Hey :wave:
First of all, this is a lovely project, thanks for creating it!
I'm just following up on @maaslalani's discord message, and adding Catppuccin alongside the default themes.
**P.S** I'm not a go programmer™ so please let me know if I've changed something that I shouldn't have!
=> feat(theme): add `Catppuccin`

README.md, spinner/examples/loading/spinner.gif
Fixes https://github.com/charmbracelet/huh/issues/65
=> fix: spinner gif not looping

field_input.go
Actually use CharLimit when set.
=> Use CharLimit in textinput

field_confirm.go, field_input.go, field_multiselect.go, field_note.go, field_select.go, field_text.go, form.go, huh_test.go, keymap.go
Change keymap depending on field position.
=> Next / Previous dynamic help

field_multiselect.go
This one should be pretty clear :wink:
=> multiselect: set height in WithHeight

examples/skip/main.go, form.go
=> prevField should not select skippable fields

field_multiselect.go
This PR fixes issue outlined in #114 .
=> fix multiselect limit in Accessible Mode

examples/go.mod, examples/go.sum, field_confirm.go, field_filepicker.go, field_input.go, field_multiselect.go, field_note.go, field_select.go, field_text.go, form.go, go.mod, go.sum, group.go
This PR introduces the `Zoom() bool` interface method for fields to implement.
This is to allow fields to request full height of the form.
=> Zoom FilePicker

spinner/spinner_test.go
=> added tests for spinner package

validate.go
This PR refers to issue #134 .
=> predefined Validation Functions

README.md
Bubbletea had a 'in the Wild' section to show off production applications, it would be nice to have the same here
=> docs(readme): `Huh?` in the Wild section

examples/readme/confirm/main.go, field_multiselect.go, field_select.go
Adds filtering on multiselect field.
=> feat: Filtering on Select and MultiSelect fields

field_filepicker.go
refs https://github.com/charmbracelet/gum/issues/626
=> fix(filepicker): not closing on close

field_select.go
ref https://github.com/charmbracelet/gum/issues/556
=> fix: wrapping selects

.golangci.yml, accessibility/accessibility.go, clamp.go, go.mod, validate.go
- update go to 1.21 (from 1.20)
- fixes some linter-reported issues
=> feat: go 1.21, lint fixes

field_filepicker.go
without this change:
with this change:
=> fix(filepicker): set padding and width to avoid cluttering

examples/go.mod, examples/go.sum, go.mod, go.sum, spinner/go.mod, spinner/go.sum
=> chore(deps): update termenv to 0.16

.github/workflows/build.yml, examples/go.mod, examples/go.sum, go.mod, go.sum
examples job is failing on #543 and #523
=> chore(deps): update bubbletea, catppuccin

form.go, huh_test.go
=> feat: expose focused field

form.go, group.go, theme.go
=> fix: form and group styles

field_filepicker.go, keymap.go
=> fix(filepicker): height, navigation

form.go, huh_test.go
`TestTimeout` fails some times, trying to figure it out.
=> fix: improve timeout

accessibility/accessibility.go, field_confirm.go, huh_test.go
closes https://github.com/charmbracelet/huh/issues/615
needs #614
=> fix: accessible default confirm value 

field_select.go
=> fix(select): do not show title if filter is set

field_select.go
=> fix(select): make sure selected item is visible on viewport update

field_input.go, field_multiselect.go, field_select.go, huh_test.go, internal/accessibility/accessibility.go
=> fix(select,multiselect): properly handle defaults and prompts

field_filepicker.go, field_select.go, field_text.go, form.go, group.go, huh_test.go, layout.go
=> fix: Terminal.app rendering issues
