- examples/bubbletea/main.go
To ensure the form is no greater than maxWidth, we need to take the minimum among the desired width and maxWidth.
Taking the maximum among these values effectively changes the logic to ensure the form is no less than maxWidth (in which case, it should probably be called minWidth).
> fix max width logic

- README.md
Hi! I changed it because the string in the sample code for [Confirm](https://github.com/charmbracelet/huh?tab=readme-ov-file#confirm) in the README and the video did not match.
> fix: confirm sample code

- README.md
The word "mode" is repeated twice in readme.
> docs: fix repeated word "mode"

- field_input.go
- field_text.go
- form.go
This PR sets the width of the `textinput` and `textarea` bubbles.
It calculates the widths from the form and horizontal frames. It also changes
the default width from 80 to the default size of the terminal with auto-resizing
if the user does not specify a Width.
> Set Width Correctly

- field_text.go
Fixes https://github.com/charmbracelet/huh/issues/63
`text` value property wasn't being updated from `textarea` value.
**before**
**after**
> fix: text value

- field_multiselect.go
- field_select.go
- option.go
Fixes https://github.com/charmbracelet/huh/issues/55
Dev notes: I had to change the value generic types to `comparable` to make the comparison between `option.Value` and the received values possible. Also, it seems more correct.
> fix: prefill select and multiselect with value

- field_multiselect.go
This adds a `Height(int)` setter to `MultiSelect` prompts.
```go
multiSelect := huh.NewMultiSelect[int]().
Options(ops...).
Height(10)
```
* When `Height <= 0` the multi-select auto-sizes itself to the number of fields (as it does currently)
* When `Height > 0` the multi-select will behave like a viewport and the visible options will scroll with the cursor
Note that the height here refers to the total height of the multi-select itself including the height of title and the description (if set) however the number of options visible will never be less than 1.
Here’s an example of it in use:
https://github.com/charmbracelet/huh/assets/25087/5c5a9cbe-1eb1-4066-bb4c-d6c69068bb77
And here's what that code looks like:
```go
package main
import (
"fmt"
"os"
"github.com/charmbracelet/huh"
)
func …
```
> feat: scrollable multi-select

- field_select.go
This adds a `Height(int)` setter to `Select` so that its contents can scroll in the same fashion as `MultiSelect` in #71.
```go
select := huh.NewSelect[int]().
Options(ops...).
Height(10)
```
> feat: scrollable select

- field_multiselect.go
- field_select.go
When `Select` or `MultiSelect` had a defined height for scrolling (kudos @meowgorithm!) and wasn't the first field in the group, the height was ignored and re-rendered only when focused.
Since the height is evaluated after the theming step, `updateViewportHeight` needs to be called in `WithTheme` and `Height` functions.
> fix: Select and MultiSelect height when unfocused

- field_multiselect.go
- huh_test.go
- keymap.go
Select has the ability to filter options, but MultiSelect doesn't, so I implemented it.
> feat: enable filtering on MultiSelect

- field_select.go
When you move the `Select` cursor to the bottom and filter for something, the whole viewport moves beyond the top.
With this fix, I clamped the offset to the view on both top and bottom.
> fix: Select viewport on filtering

- field_confirm.go
- field_input.go
- field_multiselect.go
- field_note.go
- field_select.go
- field_text.go
Fixes https://github.com/charmbracelet/huh/issues/91
Addresses issue where standalone `Run` of input would panic when run in accessible mode.
This PR fixes this issue by setting all the default themes such that there is always a theme set on stand alone inputs (when running in accessible + standalone mode)
> Set Default Theme on inputs

- examples/git/main.go
- field_input.go
- keymap.go
Fixes https://github.com/charmbracelet/huh/issues/89
This PR addes autocomplete suggestions for input fields by exposing:
```
Suggestions([]string{"foo", "bar", "baz"})
```
on `field_input`
> Expose autocomplete suggestions

- examples/hide/main.go
- form.go
- huh_test.go
the previous version was changing the page to a potentially hidden page, this PR fixes it, and covers it with tests.
> fix: shift+tab would fail if first group is hidden

- field_confirm.go
- field_input.go
- field_multiselect.go
- field_note.go
- field_select.go
- field_text.go
- form.go
- group.go
- huh_test.go
This PR allows fields to be declared as skippable as in they will not be
interactible by the users.
Currently, this is only used by the `Note`s field but can be expanded to
dynamically Skip other fields as well such as skip if the field was passed in
through a command line argument, for example.
> Skippable Fields

- form.go
currently the documentation for the [`Form.WithShowErrors()` ](https://github.com/charmbracelet/huh/blob/58163e7b5b2ffb7d60176490eda32ee4210b9d40/form.go#L170) is the same as [`Form.WithShowHelp`](https://github.com/charmbracelet/huh/blob/58163e7b5b2ffb7d60176490eda32ee4210b9d40/form.go#L181) , this fixes that.
> fix incorrect documentation for the `WithShowErrors` method

- field_note.go
This pull request fixes the issue outlined in #111  .
> Fix the overlapping style issue in render function of field_note

- examples/conditional/main.go
How we might go about officially something like this is a larger topic, but for now here's an example on how one can get started with forms that change based on user choices.
> docs(example): simple example showing conditional options

- field_text.go
This PR fixes issue discussed in #114 .
Now error will be shown if `charLimit` hits:
> fix: charlimit of text field in Accessible mode

- field_confirm.go
- field_input.go
- field_multiselect.go
- field_note.go
- field_select.go
- field_text.go
This PR makes it so that themes can be applied on individual inputs, groups, or forms.
How it works is that it simply sets the theme only if it is not already set.
This means the theme that was set first will take precendence and not be
overridden as how it currently is being overridden.
That means, if a user creates a `field.WithTheme` that will be the permanent
theme of the field, if the user creates a `group.WithTheme` that will be the
theme of each field in the group (unless it already has a theme applied by the
field individually), and so on...
> Allow theme to be set only once

- form.go
Add `WithOutput` to avoid using `tea.Options` directly with `huh?`
> WithOutput API

- examples/burger/main.go
- field_confirm.go
- field_filepicker.go
- field_input.go
- field_multiselect.go
- field_note.go
- field_select.go
- field_text.go
- form.go
- group.go
- huh_test.go
This PR allows overriding themes for fields and falls back to `ThemeCharm()` for
all inputs if no theme is specified.
---
Notes for future:
* Each field is responsible for its own style.
* Always use `activeStyles()` as theme can be `nil`.
* We may want to have some styles available for the group (`FieldSeparator` should be a field on the group, similar to `help` style), pulled when `WithTheme` is called.
> Set themes on fields

- examples/burger/main.go
- field_note.go
I'd like to be able to set the label on the note next button. This change allows this through a `WithNextLabel` func. If this isn't used, then will default to 'Next'.
> feat: optional setting of note next label

- field_multiselect.go
Fixes https://github.com/charmbracelet/gum/issues/580
- Disable the ability to toggle while filtering because they conflict and potentially cause a panic.
> fix(filtering): resolve conflict between select and filter

- form.go
Because as far as i can see, well... it's useless :)
> fix: remove useless output field in form struct

- field_input.go
- field_multiselect.go
- field_select.go
- field_text.go
- theme.go
> feat: add cursor text style

- field_input.go
When using non transparent background for char limited input text, the field weirdly fill all the layout view, resulting in a poor user interface experience.
In this example, `CharLimit` is set to `12`:
This pr adjusts its final width during the view time, letting the `WithWidth` method doing the hard job
And voila:
And before you asks, yes it supports inline mode:
> feat: adjust input width to char limit

- form.go
Implements `WithInput(r io.Reader)` which calls `tea.WithIntput(r)` and also avoids using `bubbletea` directly
Closes https://github.com/charmbracelet/huh/issues/270
> feat(form): implement `WithInput`

- form.go
Implements https://github.com/charmbracelet/huh/issues/166
> feat(form): implement WithTimeout

- form.go
I'm using `huh` to make some internal tooling with neat little TUI's. 
In this case, we have suite of tools that are their own individual `huh` forms. These can be used as top level forms, but I've also set things up in a way where forms can compose other forms that are otherwise top level. This uses a pattern commonly referred to as [Nested Tea](https://sporto.github.io/elm-patterns/architecture/nested-tea.html). Some of our tools are sometimes the top level form, other times they're forms within a form and this pattern makes them super composable.
It's a bit tricky, to compose them in this way, however. It often involves a line that looks sort of like this:
```go
if m.subFormFoo != nil && m.subFormFoo.State == huh.StateCompleted {
cmd = tea.Batch(cmd, getData(m))
m.subFormFoo = nil
} …
```
> feature suggestion: make callbacks configurable

- field_select.go
This PR adresse the following issue #173 
It allows allows use the select where the filter mode is activated when Run starts.
Thanks for telling me to also update the focus @maaslalani !
I have the following results with this code (readme example adapted a little).
```go
package main
import (
"fmt"
"github.com/charmbracelet/huh"
)
func main() {
var country string
s := huh.NewSelect[string]().
Title("Pick a country.").
Filtering(true).
Options(
huh.NewOption("United States", "US"),
huh.NewOption("Germany", "DE"),
huh.NewOption("Brazil", "BR"),
huh.NewOption("Canada", "CA"),
).
Value(&country)
huh.NewForm(huh.NewGroup(s)).Run()
fmt.Println("You chose ", country)
}
```
> feat: set filtering state of select

- accessor.go
- field_confirm.go
- field_filepicker.go
- field_input.go
- field_multiselect.go
- field_select.go
- field_text.go
- huh_test.go
This pr introduce a new (and simple) `Accessor` interface to enhance the form field values handling in a fully backward compatible way.
This interface is generic and contains only two method `Set` (for - guess what - setting value) an `Get` (you got it, for getting value).
The `Value` method of fields is very limited, and give only one way to expose fields values - via a variable pointer - with no other possibilities.
~~I propose to deprecate it in favor of an `Accessor` to define well... the field accessor :)~~
I propose a new `Accessor` method to define well... the field accessor :) Under the hood, `Value` method still exists but makes usage of an accessor.
Two generics accessors are already available:
- `EmbeddedAccessor` which replace the current behavior of fields when no variable …
> feat: introduce accessor

- form.go
- huh_test.go
This PR fixes an issue caused by #276 where aborting a form would return `ErrTimeout` instead, because when `f.timeout == 0`, `time.Since(startTime) >= f.timeout` is **always true**. This was discussed here: https://github.com/charmbracelet/huh/pull/276#discussion_r1646225089
This is fixed by simply checking if the error returned by `bubbletea` is `ErrProgramKilled`, which is already handled by `tea.WithContext(ctx)`, making the (erroneous) check unnecessary anyway.
I've also added tests for handling timeouts, user aborts, and making sure `ErrUserAborted` is returned instead of `ErrTimeout` when a timeout error occurs (the issue mentioned above). ~~This required an extra field `program` for testing to hold the `tea.Program` to send messages to the `Form` (`batchUpdate` cannot be used here …
> fix: Fix aborting a form returning a timeout error

- field_select.go
Fixed rendering of unselected options in the select field. Previously, all options were displayed with the same style regardless of their selection state. Now, unselected options will be appropriately rendered with an 'UnselectedOption' style. 
ref: https://github.com/charmbracelet/gum/issues/614
> Refactored option rendering in field_select.go to improve distinction

- field_confirm.go
- keymap.go
This patch:
-  introduces two new key bindings for the Confirm field
* Accept  - The key bindings "y/Y" for accepting 
* Reject - The key bindings  "n/N" for rejecting 
have been added to the `ConfirmKeyMap` structure in keymap.go file. 
ref: https://github.com/charmbracelet/gum/issues/568
- Centers Yes and No buttons
ref: https://github.com/charmbracelet/gum/issues/566
> Added Accept and Reject key bindings to Confirm field in Keymap.

- README.md
Hi, 
I just noticed that the 'dynamic forms' page link in the README isn´t working. 
I just made a quick fix so that it now works again :) 
Let me know if anything else is needed.
> Fix 'Dynamic forms' Page link in README

- field_input.go
- field_text.go
> **Follow up of** charmbracelet/bubbletea#1041, although they do not directly require each other.
Key binds should be checked before the key event is accepted as user input. Otherwise, control sequences or other keys might be printed instead of being interpreted as a key bind. See the above-mentioned PR for more information.
> fix: Fix invalid order of event handling in input/text fields

- form.go
- group.go
- internal/selector/selector.go
- layout.go
Use a proper type to keep track of selected items. The paginator bubble shouldn't be abused like this if it's not intended to be part of the program UI.
TODO:
> refactor: use a selector type to select items

- form.go
- group.go
- internal/selector/selector.go
- layout.go
Use selector as a generic item container that holds different types. Note: `selector.Selector` is _not_ concurrent safe.
> feat: make item selector into a slice container

- examples/multiple-groups/main.go
- field_multiselect.go
- **chore: add example of multiple groups with varying heights**
- **fix(multiselect): set viewport height in initial render**
> fix: group varying heights

- field_multiselect.go
- keymap.go
This revision changes the "toggle all" help text to "select all" and "select none" depending on what action will be performed.
https://github.com/user-attachments/assets/ca313b83-69a0-4931-9092-9e20eafd282f
Here's the source code for the above example:
```go
package main
import (
"fmt"
"os"
"github.com/charmbracelet/huh"
)
func main() {
prompt := huh.NewMultiSelect[int]().
Title("Choose stuff, will ya?").
Height(10).
Options(
huh.NewOption("Uno", 1),
huh.NewOption("Due", 2),
huh.NewOption("Tre", 3),
huh.NewOption("Quattro", 4),
huh.NewOption("Cinque", 5),
huh.NewOption("Sei", 6),
huh.NewOption("Sette", 7),
huh.NewOption("Otto", 8),
huh.NewOption("Nove", 9),
huh.NewOption("Dieci", 10),
)
f := huh.NewForm(huh.NewGroup(prompt))
if err := f.Run(); err != ni l {
fmt.Fprint(os.Stderr, "Uh oh: …
```
> feat(multiselect): contextual 'select all' help text

- spinner/spinner.go
Bug: Title Text is same white on Light background terminal
> [Bug] Fix Light Color for Spinner Title Style

- field_input.go
- group.go
if height is not set, it will never actually work properly.
refs https://github.com/charmbracelet/gum/issues/582
> fix: group size when height is 0

- field_confirm.go
This is based on https://github.com/charmbracelet/huh/pull/425, just added godoc for the linter and for some reason couldn't push to the other PR.
I'm having some issues with the golden files for the tests, so will introduce the tests in another PR. (they're currently living on the [`confirm-btn-alignment`](https://github.com/charmbracelet/huh/tree/confirm-btn-alignment) branch)
> feat: add `WithButtonAlignment` function for button positioning

- field_filepicker.go
This might close https://github.com/charmbracelet/huh/issues/399.
Further, we could use this in the [gum](https://github.com/charmbracelet/gum) file picker.
> feat: add cursor option to filepicker

- examples/filepicker-picking/main.go
- field_filepicker.go
Not sure why it was setting auto height to false, but this was causing some issues, especially when using `Picking(true)`, like gum does.
I didn't see any bad effects in removing it.
> fix(filepicker): auto-height

- accessibility/accessibility.go
If a user send EOF to stdin (Ctrl-C) in the terminal while in accessibility mode, the program gets stuck in a loop printing errors about invalid input:
> Example:
> ![CleanShot 2024-10-25 at 19 19 41](https://github.com/user-attachments/assets/abe2742c-cefd-4c6d-9eac-489420224bef)
> "oh nooo....." screams the terminal, as it decides into a demented spiral
This change isn't ideal (it'd be better to somehow bubble up an error that stops execution) but it's better than getting the process stuck in a loop. An alternative that doesn't change the signature would be to panic, or `os.Exit` or something else. Happy with whatever.
> fix(accessibility): stop scanning on EOF from stdin

- accessibility/accessibility.go
Matching the prompt of "Choose [y/N]:" default is now equal to N.
Resolves https://github.com/charmbracelet/huh/issues/264
> fix(accessibility): parseBool defaults to no

- field_multiselect.go
- field_select.go
Hi,
Currently, it isn't possible to get the filtering state of a `huh.Field`. 
I found a use case, where this can be useful. I'm using `huh` as a bubbletea bubble to highjack some key binding, but only if the form isn't filtered.
> feat: method to check filtering state of select fields

- examples/dynamic/dynamic-bubbletea/main.go
Adds example of Dynamic Huh working in Bubble Tea.
> docs: add example of Dynamic Huh? inside Bubble Tea application

- field_text.go
- huh_test.go
Adds the ability to disable the external editor option in text fields. I was looking for this feature when I noticed that someone else had asked for the same thing in issue #512
> feat: option to disable external editor in Text field

- examples/issue-522/main.go
- field_confirm.go
- group.go
- huh_test.go
- layout.go
- theme.go
- adds group styles (the bare `group lipgloss.Style` was never used)
- group keeps track of the theme now
- the groups were not using title or description anywhere
- added both title and description to the view
- fixes viewport calculations
- fixes confirm extra empty lines when no title/description
closes #522
closes #385
closes #560
> feat: group titles and descriptions

- field_multiselect.go
- field_select.go
Hi! This PR addresses a small limitation I ran into while building out a UI with this library. I was using a MultiSelect field to display a list of options, and wanted to use a Note to show additional details/context information for the option under the cursor. However, there was no way to know which option that was.
With this change, you can now write the following:
```go
items := []string{...}
ms := huh.NewMultiSelect[string]().
Options(huh.NewOptions(items...)...)
huh.NewNote().
DescriptionFunc(func() string {
currentItem := items[ms.Cursor()]
// do something with currentItem
}, onCursorUpdate{ms}) // <- see below
```
There is still the small issue of knowing when to invalidate the DescriptionFunc - I solved this by using the value of `Cursor()` as a hash:
```go
type onCursorUpdate …
```
> feat: Add Cursor() methods to Select and MultiSelect fields

- field_multiselect.go
- field_select.go
- huh_test.go
- properly render multi line items by using `lipgloss.JoinHorizontal`
- properly handle scrolling when an item has multiple lines
- added tests
closes https://github.com/charmbracelet/huh/issues/429
---
https://github.com/user-attachments/assets/c8a908a1-dfc8-4bf3-abe0-700bdb42e2d6
https://github.com/user-attachments/assets/9f951c78-daab-4445-b43d-4de56c93c904
> fix(select,multiselect): multi line items, scrolling

- README.md
In Readme, the example of using huh with bubbletea incorrectly uses the GetString method on the level field when this field is an Int.
> Fixed README GetString to GetInt for bubbletea form example

- examples/bubbletea/main.go
- examples/dynamic/dynamic-bubbletea/main.go
- examples/go.mod
- examples/go.sum
- examples/issue-275/main.go
- field_confirm.go
- field_filepicker.go
- field_input.go
- field_multiselect.go
- field_note.go
- field_select.go
- field_text.go
- form.go
- go.mod
- go.sum
- group.go
- huh_test.go
- layout.go
- theme.go
this fixes many rendering issue:
- uses the height of the taller group for the entire form unless another one is specified
- properly join lines with lipgloss (IMHO easier to reason about)
- avoid adding empty lines when not needed
- properly account for title/description when calculating heights
- properly account for framesize when calculating widths
- properly set help width 
- properly use the set theme when showing group errors
- fields actually use their height and height when rendering - this improves grid layout
- fixed note styles (will use base by default)
- maintain constant width when rendering an inline select
fixes #275 (and probably more)
closes https://github.com/charmbracelet/huh/issues/486
https://github.com/user-attachments/assets/a2fdabef-3869-4a80-8062-b51e8edccc04 …
> fix: height and width calculation improvements, wrapping

- field_confirm.go
- field_filepicker.go
- field_input.go
- field_multiselect.go
- field_note.go
- field_select.go
- field_text.go
- form.go
- huh_test.go
This way we can remove make the public interface Field implementable by 3rd parties again.
closes #663
> feat: make Field.RunAccessible public, deprecate Field.WithAccessible

- field_filepicker.go
The comment for the `DirAllowed` function incorrectly stated that it controlled whether files could be selected.
This function controls whether *directories* can be selected. This change corrects the comment to prevent confusion.
> docs(filepicker): correct godoc comment for DirAllowed function
